version: "3.5"
name: "rinha-de-backend"


services:

  # Temporary busybox container to set correct permissions to shared socket folder
  tmp:
    image: busybox
    command: sh -c "mkdir /tmp/docker && chown -R 33:33 /tmp/docker/ && chmod -R 770 /tmp/docker/"
    volumes:
      - /tmp/docker/

  load-balancer:
    image: nginx:latest
    hostname: nginx
#    user: "1000:33"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - tmp
    depends_on:
      - tmp
      - sv-01
      - sv-02
    privileged: true
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "100MB"

  sv-01: &server-base
    hostname: sv-01
#    user: "1000:33"
    build: .
    expose:
      - "8080"
    environment:
      - LMDB_PATH=/tmp
    depends_on:
      - tmp
      - redis
    volumes_from:
      - tmp
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "175MB"

  sv-02:
    hostname: sv-02
    <<: *server-base

  redis:
    image: redis:latest
    command: redis-server /etc/redis.conf
    volumes:
      - ./config/redis.conf:/etc/redis.conf:ro
    volumes_from:
      - tmp
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100MB"

volumes:
  lmdb-volume: